"""
PCA Cumulative Variance Analysis and Visualization Module.

Instead of arbitrarily selecting the number of PCA components (e.g., 50), this script empirically determines the optimal dimensionality required to 
retain 95% of the original multimodal feature variance. This systematic approach mitigates the "Curse of Dimensionality" [Bellman, 1961] while 
strictly preserving critical behavioral signals.

[Strict Data Leakage Prevention]
Crucially, the PCA fitting and variance analysis are performed exclusively on the training fold (df_train). Evaluating PCA variance on the entire 
dataset (including dev/test folds) would introduce statistical data leakage, compromising the integrity of the unseen test evaluation.
"""
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

def plot_pca_variance_curve(df_train, audio_col='audio_raw', visual_col='visual_raw'):
    """
    Code to generate PCA cumulative variance plots for Figure 4.2 in the report
    """
    # 1. Collect training data frames (train fold only)
    audio_frames = np.vstack(df_train[audio_col].dropna().values)
    visual_frames = np.vstack(df_train[visual_col].dropna().values)
    
    # 2. Scaling
    scaler_a = StandardScaler()
    audio_scaled = scaler_a.fit_transform(audio_frames)
    
    scaler_v = StandardScaler()
    visual_scaled = scaler_v.fit_transform(visual_frames)
    
    # 3. Perform PCA on full dimensionality (no limit)
    pca_audio = PCA().fit(audio_scaled)
    pca_visual = PCA().fit(visual_scaled)
    
    # 4. Compute cumulative explained variance 
    cum_var_audio = np.cumsum(pca_audio.explained_variance_ratio_)
    cum_var_visual = np.cumsum(pca_visual.explained_variance_ratio_)
    
    # --- Plot setup ---
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))
    
    # [Left] Audio PCA Graph
    ax1.plot(range(1, len(cum_var_audio) + 1), cum_var_audio, 'b-', linewidth=2)
    ax1.axhline(y=0.95, color='r', linestyle='--', label='95% Threshold')
    
    # Find the minimum number of components that exceeds 95%
    n_comp_95_audio = np.argmax(cum_var_audio >= 0.95) + 1
    ax1.axvline(x=n_comp_95_audio, color='k', linestyle=':', label=f'{n_comp_95_audio} Components')
    
    ax1.set_title('Audio Features (COVAREP + FORMANT)', fontsize=14)
    ax1.set_xlabel('Number of Components', fontsize=12)
    ax1.set_ylabel('Cumulative Explained Variance', fontsize=12)
    ax1.set_ylim([0, 1.05])
    ax1.grid(True, alpha=0.3)
    ax1.legend(loc='lower right')
    
    # [Right] Visual PCA Graph
    ax2.plot(range(1, len(cum_var_visual) + 1), cum_var_visual, 'g-', linewidth=2)
    ax2.axhline(y=0.95, color='r', linestyle='--', label='95% Threshold')
    
    n_comp_95_visual = np.argmax(cum_var_visual >= 0.95) + 1
    ax2.axvline(x=n_comp_95_visual, color='k', linestyle=':', label=f'{n_comp_95_visual} Components')
    
    ax2.set_title('Visual Features (CLNF Family)', fontsize=14)
    ax2.set_xlabel('Number of Components', fontsize=12)
    ax2.set_ylabel('Cumulative Explained Variance', fontsize=12)
    ax2.set_ylim([0, 1.05])
    ax2.grid(True, alpha=0.3)
    ax2.legend(loc='lower right')
    
    plt.tight_layout()
    plt.savefig('pca_variance_curve.pdf', format='pdf', dpi=300)
    print("Graph saved as 'pca_variance_curve.pdf'")
    plt.show()

# How to run (after loading cached data)
# df = pd.read_pickle('cache/unified/win6.0s/DAIC-WOZ_win6.0s_cache.pkl')
# df_train = df[df['fold'] == 'train']
# plot_pca_variance_curve(df_train)

# The plot_pca_variance_curve function must be defined above

# 1. Specify the path to the 6-second window cache file generated by window_sampling.py
# (Adjust the path according to your local directory)
pkl_path = "cache/temporal/win6.0s/DAIC-WOZ_win6.0s_cache.pkl" 

# 2. Load the pickle file
print("Loading data...")
df = pd.read_pickle(pkl_path)

# 3. To prevent data leakage, generate the graph using only the training data
df_train = df[df['fold'] == 'train']
print(f"Train windows loaded: {len(df_train)}")

# 4. Run the plotting function (targeting raw feature columns)
plot_pca_variance_curve(df_train, audio_col='audio_raw', visual_col='visual_raw')